# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5ef4d70f49d8b694ba815b95b82cce41d6b6f436857e9ffd4bd548263f56f54da4134b09804d44dd94d3de1f94d3233b6fc8be3d1f2f43f16e0157db22b277

test:
  secret_key_base: 1b9e0962c13fabc6e3cc1a351b8e8d92d42cf5744abe3c155a2543c4e9e1866d900188a85b303e27c7ed4ab11f08cc46877fd8f62ab33bea188554f671bece0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
